builds:
  - main: ./cmd/buffalo/main.go
    binary: buffalo
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X "github.com/gobuffalo/cli/internal/runtime.Version={{ .Tag }}"
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 6
      - 7
archives:
  - name_template: "buffalo_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    replacements:
      '386': i386
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
checksum:
  name_template: checksums.txt
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - name: 'buffalo'
    tap:
      owner: 'gobuffalo'
      name: 'homebrew-tap'
    install: |
      bin.install "buffalo"
dockers:
  - 
    image_templates:
    - gobuffalo/buffalo:{{ .Tag }}
    dockerfile: 'Dockefile.build'
    use: docker

    build_flag_templates:
    - "--build-arg=DOCKER_TAG={{.Tag}}"

  - 
    image_templates:
    - gobuffalo/buffalo:{{ .Tag }}-slim
    dockerfile: 'Dockefile.build.slim'
    use: docker
    
    build_flag_templates:
    - "--build-arg=DOCKER_TAG={{.Tag}}"

