name: Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests-off:
    name: ${{matrix.go-version}} ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: 
          - '1.16.6'
        os: 
          - 'macos-latest'
          - 'windows-latest'
          - 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.0' # The Go version to download (if necessary) and use.
      - run: go version
          
      - name: Test
        run: |
          go mod tidy -v
          go test -tags "sqlite" -cover  ./...
