name: Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests-off:
    name: ${{matrix.go-version}} ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: 
          - '^1.16.0'
        os: 
          - 'macos-latest'
          - 'windows-latest'
          - 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
          
      - name: Test
        run: |
          go mod tidy -v
          go test -tags "sqlite" -cover  ./...
