name: Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests-off:
    name: ${{matrix.go-version}} ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [macos-latest, windows-latest, ubuntu-latest]
    env:
      GO111MODULE: on
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          path: src/github.com/${{ github.repository }}
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Test
        run: |
          go mod tidy -v
          go test -tags "sqlite" -cover  ./...
